config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

 get '/pages/admin', to: "pages#index"
 post '/pages/admin', to: "pages#toggle_admin"
 delete '/pages/admin', to: "pages#destroy", :as => :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  
  has_many :projects, dependent: :destroy


  def username
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        projects_path # your path
      end
      
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
    @users = User.all
  end

  def toggle_admin()
    selected = User.find(params[:user_id])
    selected.admin = !selected.admin
    selected.save
    redirect_to "/pages/admin"
    flash[:success] = "User admin rights sucessfully toggled"
  end

  def destroy
    selected = User.find(params[:user_id])
    selected.destroy
    redirect_to "/pages/admin"
  end

 


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /projects or /projects.json
  def index
    @projects = Project.all
    @users_projects = Project.where(:user_id => current_user)
    @username = current_user.username
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  
  def after_sign_up_path_for(resource)
    '/' # Or :prefix_to_your_route
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blazecamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= stylesheet_link_tag 'title.css' %>

<div class="background">
    <div class="fullscreen"> 

        <div class="title has-text-white is-size-1 is-family-primary">
            Basecamp
        </div>
        <div>
            <% if !user_signed_in? %>
                <button class="button is-large is-info mr-3"><%= link_to 'Sign In', new_user_session_path, class: "has-text-white" %></button>
                <button class="button is-large is-info"> <%= link_to 'Sign Up', new_user_registration_path, class: "has-text-white"%></button>
            <% else %>
                <button class="button is-large is-info mr-3"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"has-text-white"%></button>
                <button class="button is-large is-info mr-3"><%= link_to 'Projects', "/projects", class:"has-text-white" %></button>
            <% end %>
            
        </div>

    </div>
</div>

app/views/pages/index.html.erb
<%= stylesheet_link_tag 'title.css' %>



<div class="fullscreen background">
    <%if current_user.admin %>
    
        <div class="columns">
            <div class="title has-text-white mr-4">Admin Page </div>
            <button class="button is-large is-info mr-3"><%= link_to 'Back to Projects', "/projects", class:"has-text-white" %></button>
        </div>
        <table class="table">
            <thead>
            <tr>
            <th><abbr title="Id">Id</abbr></th>
            <th>Username</th>
            <th><abbr title="Email">Email</abbr></th>
            <th><abbr title="Admin">Admin</abbr></th>
            <th>Toggle Admin</th>
            <th>Destroy User</th>
            </tr>
        </thead>
        <% @users.each do |user| %>
            <tr>
            <th><%= user.id %></th>
            <th><%= user.username %></th>
            <th><%= user.email %></th>
            <th><%= user.admin %></th>
            <th><%= button_to "Toggle", :method=> :post, params: {user_id: user.id}  %></th>
            <th><%= button_to "Destroy", user, :method => :delete, params: {user_id: user.id} %></th>
            </tr>
        <% end %>
        </table>
    <%else%>
        <button class="button is-large is-info mr-3"><%= link_to 'Projects', "/projects", class:"has-text-white" %></button>
        <div class="title"> Nothing here for you to see </div>
    <% end %>
 </div>





 

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, style: "display: block", class:"label" %>
    <%= form.text_field :title, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block", class:"label" %>
    <%= form.text_area :description, class:"input" %>
  </div>

  <div class="field is-grouped">
      <%= form.submit class:"button is-primary mr-1"%>
      <%= link_to "Back to Projects", projects_path, class:"button is-link" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <div class="card my-2">
  <header class="card-header has-background-primary-dark">
    <p class="card-header-title has-text-light is-size-5">
      <%= project.title %>
    </p>
    <button class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </header>
  <div class="card-content has-background-grey-lighter">
    <div class="content">
      <%= project.description %>
      <br>
      <strong>Author: <%= project.user.username%></strong>
    </div>
  </div>
  <footer class="card-footer has-text-centered has-background-primary ">
    <p class="card-footer-item ">
      <%= link_to "More", project, class: "has-text-light" %>
    </p>
  </footer>
</div>
</div>

app/views/projects/edit.html.erb
<%= stylesheet_link_tag 'title.css' %>
<div class="fullscreen">
<h1 class="title">Edit Project</h1>
<div class="columns is-centered mt-6">
<%= render "form", project: @project %>



<div>
  
</div>
</div>

app/views/projects/index.html.erb
<%= stylesheet_link_tag 'title.css' %>
<div class="projects">
    <nav class="navbar is-success" role="navigation" aria-label="main navigation">
      <div class="navbar-start">
        <div class="navbar-item">
          <%= link_to "Home", root_path, class: "button has-text-dark"%>
        </div>
      </div>
      <div class="navbar-end mr-3">
      <div class="navbar-item">
      <p class="mr-5 has-text-weight-bold">
        Hello <%= @username%>
      </p>
        <% if current_user.admin %>
          <a class="mr-1">
            <%= link_to "Admin", "/pages/admin", class: "button has-text-dark"%>
          </a>
        <%end%>
        <a class="mr-1">
          <%= link_to "Add Project", new_project_path, class: "button has-text-dark"%>
        </a>
        </div>
      </div>
    </div>
    <div class="columns mt-6 ml-2">

      <div class="column">
        <strong class="is-size-4"> All Projects </strong>
              <% @projects.each do |project| %>
                <%= render project %>
              <% end %>  
      </div>

      <div class="column">
        <strong class="is-size-4">  My Projects </strong>
              <% @users_projects.each do |project| %>
                <%= render project %>
              <% end %>  
      </div>



      

    </div>
</div>

app/views/projects/new.html.erb
<%= stylesheet_link_tag 'title.css' %>
<div class="fullscreen">
<h1 class="title">New project</h1>
<div class="columns is-centered mt-6">
<%= render "form", project: @project %>



<div>
  
</div>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'title.css' %>
  <div class="fullscreen">
  <div class="columns is-centered mt-6">
      <%= render @project %>
    <div class="box">
    <% if current_user == @project.user || current_user.admin %>
      <%= link_to "Edit", edit_project_path(@project), class:"button is-success"%>
      <%= button_to "Destroy", @project, method: :delete, class:"button is-danger" %>
    <% end %>
    <%= link_to "Back to projects", projects_path, class:"button is-primary" %>
    </div>
  </div>
</div>